// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpfur-U5XiqdT-nmABC-mXIKPdxqdoA6k',
    appId: '1:455256601959:web:19adeb588ffc8f3b41ebc2',
    messagingSenderId: '455256601959',
    projectId: 'jdcj-3b5ce',
    authDomain: 'jdcj-3b5ce.firebaseapp.com',
    storageBucket: 'jdcj-3b5ce.firebasestorage.app',
    measurementId: 'G-3VEZ6N3LQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKWDq3UJTeHPnPTL6NwvhSp_sJ4cgpLE',
    appId: '1:455256601959:android:3ecd2c17ec115a8b41ebc2',
    messagingSenderId: '455256601959',
    projectId: 'jdcj-3b5ce',
    storageBucket: 'jdcj-3b5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bZzvkGyO4v_FKQtSkxGbRVvMtBUtYMs',
    appId: '1:455256601959:ios:54a03f4ac3cc449341ebc2',
    messagingSenderId: '455256601959',
    projectId: 'jdcj-3b5ce',
    storageBucket: 'jdcj-3b5ce.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4bZzvkGyO4v_FKQtSkxGbRVvMtBUtYMs',
    appId: '1:455256601959:ios:54a03f4ac3cc449341ebc2',
    messagingSenderId: '455256601959',
    projectId: 'jdcj-3b5ce',
    storageBucket: 'jdcj-3b5ce.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpfur-U5XiqdT-nmABC-mXIKPdxqdoA6k',
    appId: '1:455256601959:web:19adeb588ffc8f3b41ebc2',
    messagingSenderId: '455256601959',
    projectId: 'jdcj-3b5ce',
    authDomain: 'jdcj-3b5ce.firebaseapp.com',
    storageBucket: 'jdcj-3b5ce.firebasestorage.app',
    measurementId: 'G-3VEZ6N3LQK',
  );
}
